"""Persistent researcher memory.

Stores researcher profile, reading history, notes, questions, and interests
in data/memory.json. This is the core differentiator - the agent learns
about the user over time and provides personalized insights.

Structure:
{
  "profile": { "name", "field", "role", "goals" },
  "interests": { "topics", "keywords", "authors", "questions" },
  "papers": { paper_id: { read_date, rating, notes, tags } },
  "insights": [ { date, type, description, papers } ],
  "conversations": [ { date, query, response } ]
}
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional

from .config import ROOT

MEMORY_PATH = ROOT / "data" / "memory.json"


@dataclass
class PaperMemory:
    """Record of interaction with a single paper."""
    paper_id: str
    title: str
    url: str
    source: str
    read_date: str
    rating: int = 0  # 1-5 stars, 0 = unrated
    notes: str = ""
    tags: List[str] = field(default_factory=list)
    related_question: str = ""


@dataclass
class Insight:
    """A proactive insight generated by the agent."""
    date: str
    insight_type: str  # "contradiction", "gap", "trend", "connection"
    description: str
    papers: List[str] = field(default_factory=list)


@dataclass
class ConversationTurn:
    """A single exchange in a conversation."""
    date: str
    user_query: str
    agent_response: str


class ResearchMemory:
    """Persistent memory for a researcher's profile and history."""

    def __init__(self, path: Path = MEMORY_PATH):
        self.path = path
        self.profile: Dict = {
            "name": "",
            "field": "",
            "role": "",
            "goals": [],
        }
        self.interests: Dict = {
            "topics": [],
            "keywords": [],
            "authors": [],
            "questions": [],
        }
        self.papers: Dict[str, PaperMemory] = {}
        self.insights: List[Insight] = []
        self.conversations: List[ConversationTurn] = []
        self._load()

    def _load(self) -> None:
        """Load memory from disk."""
        if not self.path.exists():
            return
        try:
            data = json.loads(self.path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return

        self.profile = data.get("profile", self.profile)
        self.interests = data.get("interests", self.interests)

        for pid, pdata in data.get("papers", {}).items():
            self.papers[pid] = PaperMemory(
                paper_id=pid,
                title=pdata.get("title", ""),
                url=pdata.get("url", ""),
                source=pdata.get("source", ""),
                read_date=pdata.get("read_date", ""),
                rating=pdata.get("rating", 0),
                notes=pdata.get("notes", ""),
                tags=pdata.get("tags", []),
                related_question=pdata.get("related_question", ""),
            )

        for idata in data.get("insights", []):
            self.insights.append(Insight(
                date=idata.get("date", ""),
                insight_type=idata.get("type", ""),
                description=idata.get("description", ""),
                papers=idata.get("papers", []),
            ))

        for cdata in data.get("conversations", []):
            self.conversations.append(ConversationTurn(
                date=cdata.get("date", ""),
                user_query=cdata.get("user_query", ""),
                agent_response=cdata.get("agent_response", ""),
            ))

    def save(self) -> None:
        """Persist memory to disk."""
        self.path.parent.mkdir(parents=True, exist_ok=True)

        papers_data = {}
        for pid, pm in self.papers.items():
            papers_data[pid] = {
                "title": pm.title,
                "url": pm.url,
                "source": pm.source,
                "read_date": pm.read_date,
                "rating": pm.rating,
                "notes": pm.notes,
                "tags": pm.tags,
                "related_question": pm.related_question,
            }

        insights_data = [
            {
                "date": i.date,
                "type": i.insight_type,
                "description": i.description,
                "papers": i.papers,
            }
            for i in self.insights
        ]

        conv_data = [
            {
                "date": c.date,
                "user_query": c.user_query,
                "agent_response": c.agent_response,
            }
            for c in self.conversations[-100:]  # Keep last 100 conversations
        ]

        payload = {
            "profile": self.profile,
            "interests": self.interests,
            "papers": papers_data,
            "insights": insights_data,
            "conversations": conv_data,
        }

        self.path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")

    # ── Profile Methods ──────────────────────────────────────────────────

    def set_profile(self, name: str = "", field: str = "", role: str = "", goals: List[str] = None) -> None:
        """Update researcher profile."""
        if name:
            self.profile["name"] = name
        if field:
            self.profile["field"] = field
        if role:
            self.profile["role"] = role
        if goals is not None:
            self.profile["goals"] = goals
        self.save()

    # ── Interest Methods ─────────────────────────────────────────────────

    def add_interest(self, interest_type: str, value: str) -> None:
        """Add a topic, keyword, author, or question."""
        key = interest_type + "s" if not interest_type.endswith("s") else interest_type
        if key not in self.interests:
            self.interests[key] = []
        if value not in self.interests[key]:
            self.interests[key].append(value)
            self.save()

    def remove_interest(self, interest_type: str, value: str) -> None:
        """Remove an interest."""
        key = interest_type + "s" if not interest_type.endswith("s") else interest_type
        if key in self.interests and value in self.interests[key]:
            self.interests[key].remove(value)
            self.save()

    def get_keywords(self) -> List[str]:
        """Get all keywords for search matching."""
        return self.interests.get("keywords", []) + self.interests.get("topics", [])

    # ── Paper Methods ────────────────────────────────────────────────────

    def record_paper(self, paper_id: str, title: str, url: str, source: str,
                     rating: int = 0, notes: str = "", tags: List[str] = None,
                     related_question: str = "") -> None:
        """Record that a paper was read/interacted with."""
        now = datetime.now(timezone.utc).isoformat()
        if paper_id in self.papers:
            # Update existing record
            pm = self.papers[paper_id]
            if rating:
                pm.rating = rating
            if notes:
                pm.notes = notes
            if tags:
                pm.tags = list(set(pm.tags + tags))
            if related_question:
                pm.related_question = related_question
        else:
            self.papers[paper_id] = PaperMemory(
                paper_id=paper_id,
                title=title,
                url=url,
                source=source,
                read_date=now,
                rating=rating,
                notes=notes,
                tags=tags or [],
                related_question=related_question,
            )
        self.save()

    def get_paper(self, paper_id: str) -> Optional[PaperMemory]:
        """Get memory for a specific paper."""
        return self.papers.get(paper_id)

    def get_unrated_papers(self) -> List[PaperMemory]:
        """Get papers the user hasn't rated yet."""
        return [p for p in self.papers.values() if p.rating == 0]

    def get_highly_rated(self, min_rating: int = 4) -> List[PaperMemory]:
        """Get papers rated >= min_rating."""
        return [p for p in self.papers.values() if p.rating >= min_rating]

    def get_recent_papers(self, days: int = 7) -> List[PaperMemory]:
        """Get papers read in the last N days."""
        cutoff = datetime.now(timezone.utc).timestamp() - (days * 86400)
        recent = []
        for pm in self.papers.values():
            try:
                dt = datetime.fromisoformat(pm.read_date)
                if dt.timestamp() > cutoff:
                    recent.append(pm)
            except (ValueError, TypeError):
                continue
        return sorted(recent, key=lambda p: p.read_date, reverse=True)

    # ── Insight Methods ──────────────────────────────────────────────────

    def add_insight(self, insight_type: str, description: str, papers: List[str] = None) -> None:
        """Record a new insight."""
        now = datetime.now(timezone.utc).isoformat()
        self.insights.append(Insight(
            date=now,
            insight_type=insight_type,
            description=description,
            papers=papers or [],
        ))
        self.save()

    def get_recent_insights(self, days: int = 7) -> List[Insight]:
        """Get insights from the last N days."""
        cutoff = datetime.now(timezone.utc).timestamp() - (days * 86400)
        recent = []
        for insight in self.insights:
            try:
                dt = datetime.fromisoformat(insight.date)
                if dt.timestamp() > cutoff:
                    recent.append(insight)
            except (ValueError, TypeError):
                continue
        return recent

    # ── Conversation Methods ─────────────────────────────────────────────

    def record_conversation(self, user_query: str, agent_response: str) -> None:
        """Record a conversation turn."""
        now = datetime.now(timezone.utc).isoformat()
        self.conversations.append(ConversationTurn(
            date=now,
            user_query=user_query,
            agent_response=agent_response,
        ))
        self.save()

    # ── Summary Methods ──────────────────────────────────────────────────

    def summary(self) -> str:
        """Get a human-readable summary of the researcher's profile."""
        lines = []
        p = self.profile
        if p.get("name"):
            lines.append(f"Name: {p['name']}")
        if p.get("field"):
            lines.append(f"Field: {p['field']}")
        if p.get("role"):
            lines.append(f"Role: {p['role']}")
        if p.get("goals"):
            lines.append(f"Goals: {', '.join(p['goals'])}")

        i = self.interests
        if i.get("topics"):
            lines.append(f"Topics: {', '.join(i['topics'])}")
        if i.get("keywords"):
            lines.append(f"Keywords: {', '.join(i['keywords'])}")
        if i.get("authors"):
            lines.append(f"Following: {', '.join(i['authors'])}")
        if i.get("questions"):
            lines.append(f"Open questions ({len(i['questions'])}):")
            for q in i["questions"][:5]:
                lines.append(f"  - {q}")

        lines.append(f"\nPapers read: {len(self.papers)}")
        rated = [p for p in self.papers.values() if p.rating > 0]
        if rated:
            avg = sum(p.rating for p in rated) / len(rated)
            lines.append(f"Average rating: {avg:.1f}/5")

        lines.append(f"Insights generated: {len(self.insights)}")
        lines.append(f"Conversations: {len(self.conversations)}")

        return "\n".join(lines)
